_BASE_: "../Base-RCNN-C4.yaml"
MODEL:
  PIXEL_MEAN: (0.5, 0.5, 0.5) #RGB
  PIXEL_STD: (0.5, 0.5, 0.5)  #RGB
  WEIGHTS: ""
  META_ARCHITECTURE: "WeaklySupervisedRCNNNoMeta"
  MASK_ON: False
  BACKBONE: 
    NAME: 'InceptionResNetV2'
    FREEZE_CONVS: 2
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NAME: "WSROIHeadNoMeta"
    MULTI_BOX_HEAD: False
    NUM_CLASSES: 80
    EMBEDDING_PATH: "/h/skhandel/FewshotDetection/WSASOD/data/embeddings/glove_mean"
    IN_FEATURES: ['block17']
    BATCH_SIZE_PER_IMAGE: 300
    VISUAL_ATTENTION_HEAD:
      IN_FEATURES: ['block17']
      POOLER_RESOLUTION: 17
    FAST_RCNN:
      NAME: "SupervisedDetectorOutputsBase"
      WEAK_DETECTOR:
        DETECTOR_TEMP: 2.0
        REGRESSION_BRANCH: False
  RPN:
    IN_FEATURES: ['block17']
  ROI_BOX_HEAD:
    NAME: 'InceptionResNetHead'
    POOLER_RESOLUTION: 17
    POOLER_TYPE: "ROIAlignV2"
  PROPOSAL_GENERATOR:
    NAME: "WSRPN"
INPUT:
  FORMAT: "RGB"
  NORMALIZE_IMAGES: True
  # MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TRAIN: (600,)
  MIN_SIZE_TEST: 600
DATASETS:
  TRAIN: ('coco_note_base_training_query_train',)
  TEST: ('coco_note_base_training_query_val',)
  CLASSIFIER_TRAIN: ('coco_train_2017',)
  FEWSHOT:
    TYPE: 'COCO_NOTE'
    NUM_SHOTS: 10
    SPLIT_ID: 1
    BASE_CLASSES_ID: [0, 1, 2, 3, 4, 5, 6, 8, 14, 15, 16, 17, 18, 19, 39, 56, 57, 58, 60, 62]
    NOVEL_CLASSES_ID: [7, 9, 10, 11, 12, 13, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 59, 61, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79]
DATALOADER:
  NUM_WORKERS: 2
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000  # 17.4 epochs
  IMS_PER_BATCH: 8
  CHECKPOINT_PERIOD: 500
  BASE_LR: 0.02
  REFINEMENT_LR_FACTOR: 1.0
  WARMUP_ITERS: 100
TEST:
  EVAL_PERIOD: 20000
  AUG:
    ENABLED: False